version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(dep): '
    labels:
      - dependencies
    # IMPORTANT: The group IDs are used in auto-merge workflow. Make sure to update the
    # references in your workflow to match the group IDs if you decide to change them.
    groups:
      safe-updates-version:
        applies-to: version-updates
        update-types:
          - patch
          - minor
      safe-updates-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directories:
      - /
      - /src/backend
      - /src/frontend
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(dep): '
    labels:
      - dependencies
    # IMPORTANT: The group IDs are used in auto-merge workflow. Make sure to update the
    # references in your workflow to match the group IDs if you decide to change them.
    groups:
      safe-updates-version:
        applies-to: version-updates
        update-types:
          - patch
      safe-updates-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
      safe-updates-packages:
        applies-to: version-updates
        patterns:
          - '@antfu/eslint-config'
          - '@commitlint/*'
          - '@nuxt/eslint'
          - eslint
          - lint-staged

  - package-ecosystem: docker
    directories:
      - /src/backend
      - /src/frontend
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(dep): '
    labels:
      - dependencies
    # IMPORTANT: The group IDs are used in auto-merge workflow. Make sure to update the
    # references in your workflow to match the group IDs if you decide to change them.
    groups:
      safe-updates-version:
        applies-to: version-updates
        update-types:
          - patch
      safe-updates-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
