misconfigurations:
  - id: AVD-KSV-0014
    paths:
      - k8s/common/deployment.yaml
    statement: The backend deployment needs to write to sqlite database.
  - id: AVD-KSV-0056
    paths:
      - k8s/common/rbac.yaml
    statement: The role is namespaced to mitigate risks (the devops role in needed to apply deployments from outside the cluster).

secrets:
  - id: dockerconfig-secret
    paths:
      - deployment/k8s/common/secrets.yaml
    statement: These secrets are placeholders. They are also unusable.
