services:
  frontend:
    build: .
    env_file:
      - .env
    environment:
      - NUXT_CMS_API_URL=http://backend:1337
    ports:
      - '3000:3000'

  backend:
    image: ghcr.io/this-oliver/headless-cms:latest
    env_file:
      - content/.env
    ports:
      - '1337:1337'
    volumes:
      - content/.database:/app/.database
      - content/public/uploads:/app/public/uploads
      - content/src:/app/src

  nginx:
    container_name: oliverrr-nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      # - ./logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
