services:
  frontend:
    image: ghcr.io/this-oliver/website-frontend:latest
    env_file:
      - ../src/frontend/.env
    environment:
      - NUXT_CMS_API_URL=http://backend:1337
    ports:
      - '3000:3000'

  backend:
    image: ghcr.io/this-oliver/website-backend:latest
    env_file:
      - ../src/backend/.env
    volumes:
      - ../src/backend/.database:/app/.database
      - ../src/backend/public/uploads:/app/public/uploads
      - ../src/backend/src:/app/src
    ports:
      - '1337:1337'