services:
  frontend:
    build: ./src/frontend
    env_file:
      - ./src/frontend/.env
    environment:
      - NUXT_CMS_API_URL=http://backend:1337
    expose:
      - '3000'

  backend:
    image: ghcr.io/this-oliver/headless-cms:latest
    env_file:
      - ./content/.env
    volumes:
      - ./content/.database:/app/.database
      - ./content/public/uploads:/app/public/uploads
      - ./content/src:/app/src
    expose:
      - '1337'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./ssl/your_cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./ssl/your_key.pem:/etc/ssl/private/key.pem:ro
    depends_on:
      - frontend
      - backend
