services:
  backend:
    image: ghcr.io/this-oliver/headless-cms:latest
    env_file:
      - content/.env
    ports:
      - '1337:1337'
    volumes:
      - content/.database:/app/.database
      - content/public/uploads:/app/public/uploads
      - content/src:/app/src

  nginx:
    container_name: oliverrr-nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
