apiVersion: v1
kind: ConfigMap
metadata:
  name: oliverrr-frontend
data:
  NUXT_PUBLIC_API: 'https://api.oliverrr.net'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oliverrr-backend
data:
  HOST: 0.0.0.0
  PORT: '1337'
