allowBuilds:
  '@swc/core': true
  '@swc/core@1.16.2': true
  better-sqlite3: true
  better-sqlite3@11.3.0: true
  core-js-pure: true
  core-js-pure@3.50.0: true
  esbuild: true
  esbuild@0.21.5: true
  esbuild@0.27.7: true
  sharp: true
  sharp@0.33.5: true
