services:
  frontend:
    build: ../
    env_file:
      - ../.env
    environment:
      - NUXT_CMS_API_URL=http://backend:1337
    expose:
      - '3000'

  backend:
    image: ghcr.io/this-oliver/headless-cms:latest
    env_file:
      - ../content/.env
    volumes:
      - ../content/.database:/app/.database
      - ../content/public/uploads:/app/public/uploads
      - ../content/src:/app/src
    expose:
      - '1337'

  nginx:
    container_name: oliverrr-nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
