apiVersion: apps/v1
kind: Deployment
metadata:
  name: oliverrr-frontend
  labels:
    app: oliverrr
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oliverrr
      component: frontend
  template:
    metadata:
      labels:
        app: oliverrr
        component: frontend
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: frontend
          image: ghcr.io/this-oliver/this-oliver-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: frontend-port
          env:
            - name: NUXT_CMS_API_URL
              value: 'http://oliverrr-backend:1337'
            - name: NUXT_CMS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: oliverrr-secret
                  key: FRONTEND_NUXT_CMS_API_TOKEN
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 250m
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oliverrr-backend
  labels:
    app: oliverrr
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oliverrr
      component: backend
  template:
    metadata:
      labels:
        app: oliverrr
        component: backend
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: client
          image: ghcr.io/this-oliver/this-oliver-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
              name: backend-port
          env:
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oliverrr-secret
                  key: BACKEND_ADMIN_JWT_SECRET
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: oliverrr-secret
                  key: BACKEND_API_TOKEN_SALT
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: oliverrr-secret
                  key: BACKEND_APP_KEYS
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: oliverrr-secret
                  key: BACKEND_ENCRYPTION_KEY
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: oliverrr-secret
                  key: BACKEND_TRANSFER_TOKEN_SALT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oliverrr-secret
                  key: BACKEND_JWT_SECRET
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 250m
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
