---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oliverrr-media
  labels:
    app: oliverrr
spec:
  storageClassName: homelab-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oliverrr-database
  labels:
    app: oliverrr
spec:
  storageClassName: homelab-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
