---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops
rules:
  - apiGroups: [apps]
    resources:
      - deployments
    verbs:
      - create
      - update
      - patch
      - get
      - list
  - apiGroups: [''] # "" indicates the core API group
    resources:
      - configmaps
      - persistentvolumeclaims
      - pods
      - services
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - patch
  - apiGroups: [traefik.io]
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
    verbs:
      - create
      - update
      - patch
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-apps
subjects:
  - kind: ServiceAccount
    name: cicd
roleRef:
  kind: Role
  name: devops
