---
apiVersion: v1
kind: Secret
metadata:
  name: oliverrr
type: Opaque
data:
  # The hardcoded values below are placeholders.
  BACKEND_ADMIN_JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_API_TOKEN_SALT: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_APP_KEYS: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_ENCRYPTION_KEY: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_TRANSFER_TOKEN_SALT: c3VwZXItdG9wLXNlY3JldAo=
  FRONTEND_NUXT_BACKEND_TOKEN: c3VwZXItdG9wLXNlY3JldAo=
