# Secret resource for storing sensitive information like API tokens and secrets.
apiVersion: v1
kind: Secret
metadata:
  name: oliverrr
type: Opaque
data:
  BACKEND_ADMIN_JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo= # "super-top-secret" in base64 encoding
  BACKEND_API_TOKEN_SALT: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_APP_KEYS: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo=
  FRONTEND_NUXT_API_TOKEN: c3VwZXItdG9wLXNlY3JldAo=
---
# Secret resource for storing registry credentials.
apiVersion: v1
kind: Secret
metadata:
  name: oliverrr-regcred
type: kubernetes.io/dockercfg
data:
  .dockercfg: ''
