apiVersion: v1
kind: Service
metadata:
  name: oliverrr
  labels:
    app: oliverrr

spec:
  type: NodePort
  selector:
    app: oliverrr

  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: frontend-port
    - name: backend
      protocol: TCP
      port: 1337
      targetPort: backend-port
