apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: ghcr.io/this-oliver/headless-cms:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 1000
          env:
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: BACKEND_ADMIN_JWT_SECRET
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: BACKEND_API_TOKEN_SALT
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: BACKEND_APP_KEYS
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: BACKEND_ENCRYPTION_KEY
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: BACKEND_TRANSFER_TOKEN_SALT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: BACKEND_JWT_SECRET
          ports:
            - containerPort: 1337
              name: backend-port
          resources:
            requests:
              memory: 1Gi
              cpu: '0.25'
            limits:
              memory: 2Gi
              cpu: '1'
          volumeMounts:
            - name: backend-storage
              mountPath: /app/.database
            - name: backend-storage
              mountPath: /app/public/uploads
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
          image: ghcr.io/this-oliver/this-oliver:latest
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          env:
            - name: NUXT_CMS_API_URL
              value: 'http://backend:1337'
            - name: NUXT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: frontend
                  key: FRONTEND_NUXT_API_TOKEN
          ports:
            - containerPort: 3000
              name: frontend-port
          resources:
            limits:
              memory: 256Mi
              cpu: '0.5'
            requests:
              memory: 128Mi
              cpu: '0.1'
