apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: oliverrr
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
