apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    app: all
type: kubernetes.io/dockercfg
data:
  .dockercfg: ''

---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
type: Opaque
data:
  BACKEND_ADMIN_JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_API_TOKEN_SALT: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_APP_KEYS: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_ENCRYPTION_KEY: c3VwZXItdG9wLXNlY3JldAo=
  BACKEND_TRANSFER_TOKEN_SALT: c3VwZXItdG9wLXNlY3JldAo=

---
apiVersion: v1
kind: Secret
metadata:
  name: frontend
  labels:
    app: frontend
type: Opaque
data:
  FRONTEND_NUXT_API_TOKEN: c3VwZXItdG9wLXNlY3JldAo=
