apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: oliverrr
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 1337
      targetPort: backend-port

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: oliverrr
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: frontend-port
