apiVersion: v1
kind: Service
metadata:
  name: oliverrr-frontend
  labels:
    app: oliverrr
    type: frontend
spec:
  type: NodePort
  selector:
    app: oliverrr
    type: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: frontend-port
---
apiVersion: v1
kind: Service
metadata:
  name: oliverrr-backend
  labels:
    app: oliverrr
    type: backend
spec:
  type: NodePort
  selector:
    app: oliverrr
    type: backend
  ports:
    - name: backend
      protocol: TCP
      port: 1337
      targetPort: backend-port
