apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: oliverrr

resources:
  - ../../common/
  - ingress.yaml

namePrefix: dev-oliverrr-

commonLabels:
  env: dev

patchesStrategicMerge:
  - overlay-deployment.yaml
