apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      imagePullSecrets:
        - name: dev-oliverrr-regcred
      containers:
        - name: backend
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          env:
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-oliverrr-backend
                  key: BACKEND_ADMIN_JWT_SECRET
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: dev-oliverrr-backend
                  key: BACKEND_API_TOKEN_SALT
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: dev-oliverrr-backend
                  key: BACKEND_APP_KEYS
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-oliverrr-backend
                  key: BACKEND_ENCRYPTION_KEY
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: dev-oliverrr-backend
                  key: BACKEND_TRANSFER_TOKEN_SALT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-oliverrr-backend
                  key: BACKEND_JWT_SECRET

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      imagePullSecrets:
        - name: dev-oliverrr-regcred
      containers:
        - name: frontend
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: NUXT_CMS_API_URL
              value: 'http://dev-oliverrr-backend:1337'
            - name: NUXT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dev-oliverrr-frontend
                  key: FRONTEND_NUXT_API_TOKEN
