name: Continous Deployment

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    # see https://github.com/googleapis/release-please-action/tree/a02a34c4d625f9be7cb89156071d8567266a2445/?tab=readme-ov-file#workflow-permissions
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      released: ${{ steps.release.outputs.releases_created}}
    steps:
      - name: Create release
        id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          release-type: simple

  # this job checks whether changes have been made to the frontend or backend
  # and sets the `frontend` and `backend` outputs to true or false respectively
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.check-frontend.outputs.changed }}
      backend: ${{ steps.check-backend.outputs.changed }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check for changes in frontend
        id: check-frontend
        run: echo "changed=$(git diff --name-only HEAD^ | grep '^packages/frontend/' | wc -l)" >> $GITHUB_OUTPUT

      - name: Check for changes in backend
        id: check-backend
        run: echo "changed=$(git diff --name-only HEAD^ | grep '^packages/backend/' | wc -l)" >> $GITHUB_OUTPUT

  build:
    needs: [release, pre-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read # needs write permission to push tag and release
      packages: write # needs write permission to publish Docker image
    strategy:
      matrix:
        app: [frontend, backend]
        include:
          - app: frontend
            condition: ${{ needs.pre-build.outputs.frontend == '1' }}
          - app: backend
            condition: ${{ needs.pre-build.outputs.backend == '1' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Login to registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build ${{ matrix.app }} container image
        if: ${{ needs.release.outputs.released != 'true' }}
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: packages/${{ matrix.app }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:latest
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          platforms: linux/amd64,linux/arm64

      - name: Build ${{ matrix.app }} container image for Release
        if: ${{ needs.release.outputs.released == 'true' }}
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: packages/${{ matrix.app }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:${{ needs.release.outputs.tag }}
            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:latest
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          platforms: linux/amd64,linux/arm64
