name: Continous Deployment

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - k8s/**
      - package*.json
  workflow_dispatch:
    inputs:
      build:
        description: Trigger build
        type: boolean
        required: false
        default: true
      deploy:
        description: Trigger deploy
        type: boolean
        required: false
        default: true

jobs:
  release:
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest
    # see https://github.com/googleapis/release-please-action/tree/a02a34c4d625f9be7cb89156071d8567266a2445/?tab=readme-ov-file#workflow-permissions
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      released: ${{ steps.release.outputs.releases_created}}
    steps:
      - name: Create release
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          release-type: node

  build:
    if: ${{ always() && (needs.release.outputs.released == 'true' || inputs.build == true) }}
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read # needs write permission to push tag and release
      packages: write # needs write permission to publish Docker image
    strategy:
      matrix:
        app: [frontend, backend]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Login to registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ vars.REGISTRY_SERVER }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Build ${{ matrix.app }} container image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          push: true
          context: ./src/${{ matrix.app }}
          file: ./src/${{ matrix.app }}/Dockerfile
          tags: |
            ${{ vars.REGISTRY_SERVER }}/${{ github.repository_owner }}/website-${{ matrix.app }}:${{ needs.release.outputs.tag || 'latest' }}
            ${{ vars.REGISTRY_SERVER }}/${{ github.repository_owner }}/website-${{ matrix.app }}:latest
            ${{ vars.REGISTRY_SERVER }}/${{ github.repository_owner }}/website-${{ matrix.app }}:${{ github.sha }}
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          platforms: linux/amd64,linux/arm64

  deploy:
    if: ${{ needs.release.outputs.released == 'true' || inputs.deploy == true }}
    needs: [release, build]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.release.outputs.released == 'true' && 'production' || 'development' }}
    permissions:
      contents: read
      packages: read
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
      DEPLOYMENT_ENV: ${{ needs.release.outputs.released == 'true' && 'prod' || 'dev' }}
    steps:
      - name: Install Kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.37/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.37/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update && sudo apt-get install -y kubectl

          kubectl version --client

      - name: Configure Kubectl
        env:
          CLUSTER_CONTEXT: k8s
          CLUSTER_HOST: ${{ secrets.CLUSTER_HOST }}
          CLUSTER_PORT: ${{ secrets.CLUSTER_PORT }}
          SERVICE_ACCOUNT_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        run: |
          kubectl config set-cluster "${CLUSTER_CONTEXT}-cluster" --server="https://${CLUSTER_HOST}:${CLUSTER_PORT}" --insecure-skip-tls-verify
          kubectl config set-credentials "${CLUSTER_CONTEXT}-user" --token "$SERVICE_ACCOUNT_TOKEN"
          kubectl config set-context "${CLUSTER_CONTEXT}-context" --cluster="${CLUSTER_CONTEXT}-cluster" --user="${CLUSTER_CONTEXT}-user" --namespace="$NAMESPACE"
          kubectl config use-context "${CLUSTER_CONTEXT}-context"

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Apply resources
        run: |
          kubectl -n "$NAMESPACE" apply -k "k8s/env/${DEPLOYMENT_ENV}"

      - name: Patch secrets
        run: |
          kubectl create secret generic "oliverrr-${DEPLOYMENT_ENV}" \
            --from-literal=BACKEND_ADMIN_JWT_SECRET='${{ secrets.BACKEND_ADMIN_JWT_SECRET }}' \
            --from-literal=BACKEND_API_TOKEN_SALT='${{ secrets.BACKEND_API_TOKEN_SALT }}' \
            --from-literal=BACKEND_APP_KEYS='${{ secrets.BACKEND_APP_KEYS }}' \
            --from-literal=BACKEND_JWT_SECRET='${{ secrets.BACKEND_JWT_SECRET }}' \
            --from-literal=BACKEND_ENCRYPTION_KEY='${{ secrets.BACKEND_ENCRYPTION_KEY }}' \
            --from-literal=BACKEND_TRANSFER_TOKEN_SALT='${{ secrets.BACKEND_TRANSFER_TOKEN_SALT }}' \
            --from-literal=FRONTEND_NUXT_CMS_API_TOKEN='${{ secrets.FRONTEND_NUXT_CMS_API_TOKEN }}' \
            --dry-run=client -o yaml | kubectl -n "$NAMESPACE" apply -f -

      - name: Patch container images
        run: |
          tag="latest"
          if [[ "${{ needs.release.outputs.released }}" == "true" ]]; then
            tag="${{ needs.release.outputs.tag }}"
          elif [[ "${{ inputs.build }}" == "true" ]]; then
            tag="${{ github.sha }}"
          fi

          kubectl -n "$NAMESPACE" set image deployment/oliverrr-frontend-${{ steps.set-env.outputs.environment }} frontend=ghcr.io/this-oliver/website-frontend:${tag}
          kubectl -n "$NAMESPACE" set image deployment/oliverrr-backend-${{ steps.set-env.outputs.environment }} backend=ghcr.io/this-oliver/website-backend:${tag}

      - name: Restart deployments
        run: |
          kubectl rollout restart deployment/oliverrr-frontend-${{ steps.set-env.outputs.environment }}
          kubectl rollout restart deployment/oliverrr-backend-${{ steps.set-env.outputs.environment }}
