name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # fetch all history for commitlint

      - name: Setup PNPM + Node
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm lint

      - name: Lint Commits
        run: pnx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Lint PR Title
        run: echo "${{ github.event.pull_request.title }}" | pnx commitlint --verbose

  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup PNPM + Node
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0

      - name: Install root dependencies
        run: pnpm install

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: src/frontend

      - name: Install backend dependencies
        run: pnpm install
        working-directory: src/backend

      - name: Check for vulnerable dependencies, misconfigurations, and secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: 'vuln,misconfig,secret'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: 0
        env:
          TRIVY_IGNOREFILE: .trivyignore.yaml
