name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # fetch all history for commitlint

      - name: Setup PNPM + Node
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm lint

      - name: Lint Commits
        run: pnx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Lint PR Title
        run: echo "${{ github.event.pull_request.title }}" | pnx commitlint --verbose

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [frontend, backend]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Gather timestamp
        run: echo "TIMESTAMP=$(date)>>GITHUB_ENV"

      - name: Build ${{ matrix.app }} container image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          push: false
          context: ./src/${{ matrix.app }}
          file: ./src/${{ matrix.app }}/Dockerfile
          tags: |
            ${{ vars.REGISTRY_SERVER }}/${{ github.repository_owner }}/website-${{ matrix.app }}:${{ github.sha }}
          build-args: |
            APP_VERSION=${{ github.sha }}
            APP_COMMIT_SHA=${{ github.sha }}
            APP_BUILD_TIMESTAMP=$TIMESTAMP
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          platforms: linux/amd64,linux/arm64

  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup PNPM + Node
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          working-directory: ${{ matrix.app }}

      - name: Install dependencies in root
        run: pnpm install
        working-directory: .

      - name: Install dependencies in frontend
        run: pnpm install
        working-directory: src/frontend

      - name: Install dependencies in backend
        run: pnpm install
        working-directory: src/backend

      - name: Check for vulnerable dependencies, misconfigurations, and secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
        with:
          scan-type: fs
          scan-ref: ${{ matrix.app }}
          scanners: 'vuln,misconfig,secret'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: 0
        env:
          TRIVY_IGNOREFILE: .trivyignore.yaml
